/**
 * EventMockData.ts — Mock Data for Event Module Development
 */
import type { Event } from './EventTypes';

export const MOCK_EVENTS: Event[] = [
  {
    id: 'evt-001',
    eventName: 'Sharma-Patel Wedding',
    eventType: 'WEDDING',
    eventDate: '2026-03-15',
    clientName: 'Rajesh Sharma',
    clientPhone: '+91 98765 43210',
    venueName: 'The Grand Palace',
    venueAddress: '123 MG Road, Bangalore',
    estimatedGuestCount: 500,
    budget: 250000,
    colorTheme: 'Blush Pink & Gold',
    moodNotes: 'Elegant, traditional with modern touches. Lots of roses and marigolds.',
    moodBoardLink: 'https://pinterest.com/board/123',
    assignedDesigner: 'Meera Patel',
    status: 'CONFIRMED',
    internalNotes: 'VIP client - repeat customer. Provide premium service.',
    createdAt: '2026-01-10T10:30:00Z',
  },
  {
    id: 'evt-002',
    eventName: 'TechCorp Annual Gala',
    eventType: 'CORPORATE',
    eventDate: '2026-02-28',
    clientName: 'Priya Menon',
    clientPhone: '+91 87654 32109',
    venueName: 'IT Park Convention Center',
    venueAddress: 'Whitefield, Bangalore',
    estimatedGuestCount: 200,
    budget: 150000,
    colorTheme: 'White & Blue',
    moodNotes: 'Minimalist, professional look. Orchids and lilies preferred.',
    assignedDesigner: 'Ananya Sharma',
    status: 'IN_PRODUCTION',
    createdAt: '2026-01-15T14:00:00Z',
  },
  {
    id: 'evt-003',
    eventName: 'Gupta Birthday Celebration',
    eventType: 'PARTY',
    eventDate: '2026-02-20',
    clientName: 'Amit Gupta',
    clientPhone: '+91 76543 21098',
    venueName: 'Lakeview Resort',
    estimatedGuestCount: 75,
    budget: 45000,
    colorTheme: 'Rainbow',
    moodNotes: '50th birthday party. Fun and colorful theme.',
    assignedDesigner: 'Priya Gupta',
    status: 'QUOTED',
    createdAt: '2026-02-01T09:00:00Z',
  },
  {
    id: 'evt-004',
    eventName: 'Rao Memorial Service',
    eventType: 'FUNERAL',
    eventDate: '2026-02-19',
    clientName: 'Suresh Rao',
    clientPhone: '+91 65432 10987',
    venueName: 'Peaceful Gardens',
    venueAddress: 'JP Nagar, Bangalore',
    budget: 25000,
    colorTheme: 'White',
    moodNotes: 'Peaceful, dignified arrangements. White lilies and chrysanthemums.',
    assignedDesigner: 'Kavita Reddy',
    status: 'CONFIRMED',
    internalNotes: 'Handle with sensitivity.',
    createdAt: '2026-02-17T16:00:00Z',
  },
  {
    id: 'evt-005',
    eventName: 'Kapoor-Singh Wedding',
    eventType: 'WEDDING',
    eventDate: '2026-04-10',
    clientName: 'Neha Kapoor',
    clientPhone: '+91 54321 09876',
    venueName: 'Royal Gardens',
    venueAddress: 'Indiranagar, Bangalore',
    estimatedGuestCount: 350,
    budget: 180000,
    colorTheme: 'Red & White',
    moodNotes: 'Traditional North Indian wedding. Grand mandap decoration needed.',
    status: 'INQUIRY',
    createdAt: '2026-02-18T11:30:00Z',
  },
  {
    id: 'evt-006',
    eventName: 'Reddy Anniversary',
    eventType: 'PARTY',
    eventDate: '2026-03-01',
    clientName: 'Lakshmi Reddy',
    clientPhone: '+91 43210 98765',
    venueName: 'Home - HSR Layout',
    estimatedGuestCount: 30,
    budget: 15000,
    colorTheme: 'Silver & White',
    moodNotes: '25th anniversary. Intimate gathering.',
    assignedDesigner: 'Meera Patel',
    status: 'CONFIRMED',
    createdAt: '2026-02-10T08:00:00Z',
  },
  {
    id: 'evt-007',
    eventName: 'StartupX Product Launch',
    eventType: 'CORPORATE',
    eventDate: '2026-03-20',
    clientName: 'Vikram Joshi',
    clientPhone: '+91 32109 87654',
    venueName: 'Tech Hub Auditorium',
    venueAddress: 'Koramangala, Bangalore',
    estimatedGuestCount: 150,
    budget: 80000,
    colorTheme: 'Green & Black',
    moodNotes: 'Modern, tech-forward aesthetic. Succulents and geometric arrangements.',
    status: 'QUOTED',
    createdAt: '2026-02-14T13:00:00Z',
  },
  {
    id: 'evt-008',
    eventName: 'Nair-Das Wedding',
    eventType: 'WEDDING',
    eventDate: '2026-05-05',
    clientName: 'Anand Nair',
    clientPhone: '+91 21098 76543',
    venueName: 'Beach Resort',
    venueAddress: 'ECR, Chennai',
    estimatedGuestCount: 250,
    budget: 300000,
    colorTheme: 'Teal & Coral',
    moodNotes: 'Beach wedding. Tropical flowers, bohemian style.',
    moodBoardLink: 'https://pinterest.com/board/456',
    assignedDesigner: 'Ananya Sharma',
    status: 'INQUIRY',
    createdAt: '2026-02-16T15:00:00Z',
  },
  {
    id: 'evt-009',
    eventName: 'Kumar Housewarming',
    eventType: 'OTHER',
    eventDate: '2026-02-25',
    clientName: 'Sanjay Kumar',
    clientPhone: '+91 10987 65432',
    venueName: 'New Villa - Sarjapur',
    estimatedGuestCount: 50,
    budget: 20000,
    colorTheme: 'Yellow & Orange',
    moodNotes: 'Traditional pooja arrangements + entrance decoration.',
    assignedDesigner: 'Priya Gupta',
    status: 'CONFIRMED',
    createdAt: '2026-02-12T10:00:00Z',
  },
  {
    id: 'evt-010',
    eventName: 'Cancelled: Old Event',
    eventType: 'WEDDING',
    eventDate: '2026-01-20',
    clientName: 'Test Client',
    clientPhone: '+91 00000 00000',
    venueName: 'Test Venue',
    status: 'CANCELLED',
    internalNotes: 'Client cancelled due to date change.',
    createdAt: '2025-12-15T10:00:00Z',
  },
];

// ─── Stats Helper ───────────────────────────────────────────

export const getEventStats = (events: Event[]) => {
  const now = new Date();
  const thisMonth = now.getMonth();
  const thisYear = now.getFullYear();

  return {
    total: events.length,
    thisMonth: events.filter((e) => {
      const d = new Date(e.eventDate);
      return d.getMonth() === thisMonth && d.getFullYear() === thisYear;
    }).length,
    inquiries: events.filter((e) => e.status === 'INQUIRY').length,
    confirmed: events.filter((e) => e.status === 'CONFIRMED').length,
    inProduction: events.filter((e) => e.status === 'IN_PRODUCTION').length,
    totalBudget: events
      .filter((e) => e.status !== 'CANCELLED')
      .reduce((sum, e) => sum + (e.budget ?? 0), 0),
  };
};
