using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Sumpooj.Infrastructure.Migrations
{
    /// <summary>
    /// Adds the Barcodes table backing the Cloud Barcode foundation
    /// (Manufacturer + Internal barcodes per Product, company-scoped).
    ///
    /// NOTE: hand-authored rather than tool-generated. During development the
    /// design-time ModelSnapshot (SumpoojDbContextModelSnapshot.cs) was found
    /// to already be out of sync with the migration history for entities
    /// unrelated to this feature (pre-existing drift, not caused by this
    /// change), and was subsequently found missing from the Migrations
    /// folder entirely. Auto-generating via `dotnet ef migrations add` in
    /// that state would have bundled unrelated schema changes into this
    /// migration or produced a full-schema recreation. This file contains
    /// ONLY the Barcodes table so it can be reviewed and applied in
    /// isolation. `dotnet ef database update` does not require the
    /// snapshot (design-time only); however the snapshot should be
    /// regenerated by someone with real database access before the next
    /// `dotnet ef migrations add` is run for an unrelated feature.
    /// </summary>
    public partial class AddBarcodesTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Barcodes",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CompanyId = table.Column<Guid>(type: "uuid", nullable: false),
                    ProductId = table.Column<Guid>(type: "uuid", nullable: false),
                    Type = table.Column<int>(type: "integer", nullable: false),
                    Value = table.Column<string>(type: "text", nullable: false),
                    CreatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAtUtc = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Barcodes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Barcodes_Products_ProductId",
                        column: x => x.ProductId,
                        principalTable: "Products",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            // A barcode Value is unique within a company: Company A + "ABC123"
            // and Company B + "ABC123" may coexist, but not twice for the same company.
            migrationBuilder.CreateIndex(
                name: "IX_Barcodes_CompanyId_Value",
                table: "Barcodes",
                columns: new[] { "CompanyId", "Value" },
                unique: true);

            // At most one barcode per (Product, Type): a product cannot have
            // two Manufacturer barcodes or two Internal barcodes at once.
            migrationBuilder.CreateIndex(
                name: "IX_Barcodes_ProductId_Type",
                table: "Barcodes",
                columns: new[] { "ProductId", "Type" },
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "Barcodes");
        }
    }
}
